# Generated by Django 6.1.1 on 2026-09-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена, руб.')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать в прайсе')),
            ],
            options={
                'verbose_name': 'Услуга (прайс-лист)',
                'verbose_name_plural': 'Прайс-лист',
                'ordering': ('position', 'id'),
            },
        ),
    ]
