# Generated by Django 6.1.1 on 2026-09-20 12:40

import django.utils.timezone
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст уведомления')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=32, unique=True, verbose_name='Номер заявки')),
                ('order_type', models.CharField(choices=[('MONTAZH', 'Монтаж'), ('ZAMER', 'Замер'), ('REMONT', 'Ремонт / доработка'), ('DEMONTAZH', 'Демонтаж')], default='MONTAZH', max_length=20, verbose_name='Тип заявки')),
                ('status', models.CharField(choices=[('WAITING_CALL', 'Ожидает звонок'), ('WAITING_SERVICE', 'Ожидает услугу'), ('IN_PROGRESS', 'В работе'), ('DONE', 'Завершен'), ('CANCELED', 'Отменен')], default='WAITING_CALL', max_length=20, verbose_name='Статус заявки')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=50, verbose_name='Дом')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий магазина')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('manager_name', models.CharField(blank=True, max_length=255, verbose_name='Менеджер')),
                ('manager_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон менеджера')),
                ('specialist_name', models.CharField(blank=True, max_length=255, verbose_name='Специалист по монтажу')),
                ('specialist_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон специалиста')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Желаемая дата (с)')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Желаемая дата (по)')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Дата назначения работ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заявки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=orders.models.order_file_path, verbose_name='Файл')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('uploaded_by_role', models.CharField(choices=[('STORE', 'Магазин'), ('MANAGER', 'Менеджер')], default='STORE', max_length=10, verbose_name='Сторона')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Файл заявки',
                'verbose_name_plural': 'Файлы заявок',
                'ordering': ('uploaded_at', 'id'),
            },
        ),
    ]
