"""
Django settings for pro_montazh project.

Generated by 'django-admin startproject' using Django 5.x.
"""

from pathlib import Path

# Строим пути внутри проекта: BASE_DIR указывает на папку pro_montazh/
BASE_DIR = Path(__file__).resolve().parent.parent


# ==============================================================================
# ОСНОВНЫЕ НАСТРОЙКИ (DEVELOPMENT)
# ==============================================================================

# ВНИМАНИЕ: держите секретный ключ в тайне в продакшене!
SECRET_KEY = 'django-insecure-change-this-key-to-your-own-secret-key-in-production'

# Отладка включена для локальной разработки
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '[::1]', '0.0.0.0']


# ==============================================================================
# ПРИЛОЖЕНИЯ
# ==============================================================================

INSTALLED_APPS = [
    # Стандартные приложения Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Сторонние библиотеки
    'rest_framework',

    # Пользовательские приложения проекта
    'users.apps.UsersConfig',
    'orders.apps.OrdersConfig',
    'services.apps.ServicesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Указываем путь к общей папке templates
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'orders.context_processors.unread_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# ==============================================================================
# БАЗА ДАННЫХ (SQLite для локальной разработки)
# ==============================================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ==============================================================================
# КАСТОМНАЯ МОДЕЛЬ ПОЛЬЗОВАТЕЛЯ И АВТОРИЗАЦИЯ
# ==============================================================================

AUTH_USER_MODEL = 'users.User'

# Куда перенаправлять после входа/выхода
AUTHENTICATION_BACKENDS = [
    'users.backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'profile'
LOGOUT_REDIRECT_URL = 'login'


# ==============================================================================
# ВАЛИДАЦИЯ ПАРОЛЕЙ
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==============================================================================
# ЯЗЫК И ВРЕМЕННЫЕ ЗОНЫ
# ==============================================================================

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# ==============================================================================
# СТАТИКА И МЕДИАФАЙЛЫ (CSS, JS, Загрузки)
# ==============================================================================

# Настройки статических файлов (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Настройки для загружаемых пользователем файлов (акты, прайсы, фото)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ==============================================================================
# ДЕФОЛТНОЕ ПОЛЕ ДЛЯ ПЕРВИЧНЫХ КЛЮЧЕЙ
# ==============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# ЗАГРУЗКА ФАЙЛОВ
# ==============================================================================

# Максимальный размер файла, который магазин может прикрепить к заявке (20 МБ)
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
